import type { Metadata } from "next"
import "./globals.css"
import { AppHeader, AppFooter } from "@/components/common"
import Providers from "./providers"
import { Toaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className="antialiased">
        <Providers>
          <div className="page">
            <AppHeader />
              <div className="container">{children}</div>
            <AppFooter />
          </div>
          <Toaster />
        </Providers>
      </body>
    </html>
  )
}
